create table if not exists public.rsvps (
  id bigint generated by default as identity primary key,
  guest_name text not null,
  email text not null,
  attendance text not null check (attendance in ('attending', 'not_attending')),
  guests_count integer not null default 1 check (guests_count between 1 and 10),
  message text,
  created_at timestamptz not null default now()
);

alter table public.rsvps enable row level security;

create policy "Anyone can submit RSVP"
on public.rsvps
for insert
to anon
with check (true);

-- Intentionally no public SELECT policy: guests can submit but cannot read the RSVP list.